<?php


	$servername = "localhost";
    $username = "root";
    $password = "";
    $db = "team2";

    // Create connection
    $con = mysqli_connect($servername, $username, $password,$db);

    // Check connection
    if (!$con) {
      die("Connection failed: " . mysqli_connect_error());
    }


 session_start();

 if(isset($_SESSION["uid"]))
 
{ $id=$_SESSION["uid"];
  $file=$_GET["f"];



  $sql = "SELECT * FROM `visitor` where file='$file'";
  $run_query=mysqli_query($con,$sql);
if(mysqli_num_rows($run_query) > 0 )
{ 
  while($row = mysqli_fetch_array($run_query)){
       $name=$row["name"];
       $num=$row["number"];
       $city=$row["city"];
       $address=$row["address"];
       $dd=$row["date"];
       $gid=$row["gid"];
       $purpose=$row["purpose"];
       $gate=$row["gate"];
       $fname=$row["fname"];
    }

   }

    $sql = "SELECT * FROM `admin` where id='$gid'";
  $run_query=mysqli_query($con,$sql);

    if(mysqli_num_rows($run_query) > 0 )
    { 
        while($row = mysqli_fetch_array($run_query)){
         $first=$row["first"];
         $second=$row["second"];
      
      }

   }

date_default_timezone_set("Asia/Kolkata");

}
else
header('Location:index.php');

?>


<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="font-awesome.min.css">
<script type="text/javascript" src = "./js/jquery.js"></script>
<script type="text/javascript">
    function printData()
    {
   var divToPrint=document.getElementById("card1");
   newWin= window.open("");
   newWin.document.write(divToPrint.outerHTML);
   newWin.print();
   newWin.close();
    }
</script>
<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 500px;
  margin: auto;
  text-align: center;
  font-family: arial;
    padding: 20px;  
    background-color: white;
}

.title {
  color: grey;
  font-size: 18px;
}
 
    .dt{
        padding-left: 40px;
    } 
    .lst{
        font-size: 5px;
    }
button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}
    body{
        background-color: ghostwhite;
    }
    
  

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}
</style>
</head>
<body>

<h2 style="text-align:center">Visitor Card</h2>

<div class="card">
  
       <img width="60%" height="60%" src="images/gl.png">
       <br><br>

      <?php echo "<img src='photo/$file' style='width:150px;height:150px'/>"; ?>
      <table align=center>
          <tbody style="text-align:left;">
              <tr>
                  <td style="width: 40%;"><b>Student Name </b></td>
                  <td style="width: 80%;align-left: 0px;"><?php echo " : $name"?></td>
              </tr>
              <tr>
                  <td style="width: 40%;"><b>Fathers Name </b></td>
                  <td style="width: 80%;align-left: 0px;"><?php echo " : $fname"?></td>
              </tr>
              <tr>
                  <td style="width: 40%;"><b>Contact </b></td>
                  <td style="width: 80%;"><?php echo " : $num"?></td>
              </tr>
              <tr>
                  <td style="width: 40%;"><b>Address </b></td>
                  <td style="width: 80%;"><?php echo " : $address"?></td>
              </tr>
              <tr>
                  <td style="width: 40%;"><b>Place </b></td>
                  <td style="width: 80%;"><?php echo " : $city"?></td>
              </tr>
              <tr>
                  <td style="width: 40%;"><b>Purpose </b></td>
                  <td style="width: 80%;"><?php echo " : $purpose"?></td>
              </tr>
          </tbody>
      </table>

       <div class="dt">
      <table align=center > 
    <tbody>
    <tr>
    <td style="width: 50%;"><p class="title"><?php echo "Date : " .date("d/m/Y");?></p></td>
    <td style="width: 50%; margin-left:50px;"><p class="title"><?php echo "" .date("h:i a" ,time()+3240);?></td>
    </tr>
          </tbody>
        </table>
      </div>

      <p><SPAN STYLE="COLOR:Red">NOTE: This pass is valid for 1 Day only!</SPAN></p>
      <div style= "float:right">
      
    <p class="title" style="font-size:10px;"><?php echo "Generated by : $first $second";?></p>
        <p class="title" style="font-size:10px;float:right;"><?php echo " $gate";?></p>
      </div>
   
 <p><button onclick="printData();">Print</button></p>

 <p><a href="register.php"><button>NEW VISITOR</button></a></p>
</div>

</body>
</html>



